import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Hero from "@/component/sections/Hero";
import Navs from "@/component/sections/Navs";
import { Box } from "@mui/material";
import SmallNavs from "@/component/sections/SmallNavs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Box
          sx={{
            overflowX: "hidden",
            backgroundColor: "#FFFFFF",
            width: "100%",
            height: "100%",
          }}
        >
          <Hero />
          <Navs />
          <SmallNavs />
          {children}
        </Box>
      </body>
    </html>
  );
}
