import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Hero from "@/component/sections/Hero";
import Navs from "@/component/sections/Navs";
import { Box } from "@mui/material";
import SmallNavs from "@/component/sections/SmallNavs";
import Footer from "@/component/sections/Footer";

const outfitSans = Outfit({
  variable: "--font-outfit-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfitSans.variable} antialiased`}>
        <Box
          sx={{
            overflowX: "hidden",
            backgroundColor: "#FFFFFF",
            width: "100%",
            height: "100%",
          }}
        >
          <Hero />
          <Navs />
          <SmallNavs />
          {children}
          <Footer />
        </Box>
      </body>
    </html>
  );
}
