import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import Main from "@/component/Main";
import "./globals.css";

const outfitSans = Outfit({
  variable: "--font-outfit-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PropTech Philipines",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfitSans.variable} antialiased`}>
        <Main>{children}</Main>
      </body>
    </html>
  );
}
